// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/config/filter/http/header_to_metadata/v2/header_to_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Config.Filter.Http.HeaderToMetadata.V2 {

  /// <summary>Holder for reflection information generated from envoy/config/filter/http/header_to_metadata/v2/header_to_metadata.proto</summary>
  public static partial class HeaderToMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/config/filter/http/header_to_metadata/v2/header_to_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HeaderToMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkdlbnZveS9jb25maWcvZmlsdGVyL2h0dHAvaGVhZGVyX3RvX21ldGFkYXRh",
            "L3YyL2hlYWRlcl90b19tZXRhZGF0YS5wcm90bxIuZW52b3kuY29uZmlnLmZp",
            "bHRlci5odHRwLmhlYWRlcl90b19tZXRhZGF0YS52MhoXdmFsaWRhdGUvdmFs",
            "aWRhdGUucHJvdG8i7gQKBkNvbmZpZxJSCg1yZXF1ZXN0X3J1bGVzGAEgAygL",
            "MjsuZW52b3kuY29uZmlnLmZpbHRlci5odHRwLmhlYWRlcl90b19tZXRhZGF0",
            "YS52Mi5Db25maWcuUnVsZRJTCg5yZXNwb25zZV9ydWxlcxgCIAMoCzI7LmVu",
            "dm95LmNvbmZpZy5maWx0ZXIuaHR0cC5oZWFkZXJfdG9fbWV0YWRhdGEudjIu",
            "Q29uZmlnLlJ1bGUaoQEKDEtleVZhbHVlUGFpchIaChJtZXRhZGF0YV9uYW1l",
            "c3BhY2UYASABKAkSFgoDa2V5GAIgASgJQgm66cADBHICIAESDQoFdmFsdWUY",
            "AyABKAkSTgoEdHlwZRgEIAEoDjJALmVudm95LmNvbmZpZy5maWx0ZXIuaHR0",
            "cC5oZWFkZXJfdG9fbWV0YWRhdGEudjIuQ29uZmlnLlZhbHVlVHlwZRrxAQoE",
            "UnVsZRIZCgZoZWFkZXIYASABKAlCCbrpwAMEcgIgARJeChFvbl9oZWFkZXJf",
            "cHJlc2VudBgCIAEoCzJDLmVudm95LmNvbmZpZy5maWx0ZXIuaHR0cC5oZWFk",
            "ZXJfdG9fbWV0YWRhdGEudjIuQ29uZmlnLktleVZhbHVlUGFpchJeChFvbl9o",
            "ZWFkZXJfbWlzc2luZxgDIAEoCzJDLmVudm95LmNvbmZpZy5maWx0ZXIuaHR0",
            "cC5oZWFkZXJfdG9fbWV0YWRhdGEudjIuQ29uZmlnLktleVZhbHVlUGFpchIO",
            "CgZyZW1vdmUYBCABKAgiIwoJVmFsdWVUeXBlEgoKBlNUUklORxAAEgoKBk5V",
            "TUJFUhABQgRaAnYyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config), global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Parser, new[]{ "RequestRules", "ResponseRules" }, null, new[]{ typeof(global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.ValueType) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair), global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair.Parser, new[]{ "MetadataNamespace", "Key", "Value", "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule), global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule.Parser, new[]{ "Header", "OnHeaderPresent", "OnHeaderMissing", "Remove" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Config : pb::IMessage<Config> {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.HeaderToMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config(Config other) : this() {
      requestRules_ = other.requestRules_.Clone();
      responseRules_ = other.responseRules_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "request_rules" field.</summary>
    public const int RequestRulesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> _repeated_requestRules_codec
        = pb::FieldCodec.ForMessage(10, global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> requestRules_ = new pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule>();
    /// <summary>
    /// The list of rules to apply to requests.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> RequestRules {
      get { return requestRules_; }
    }

    /// <summary>Field number for the "response_rules" field.</summary>
    public const int ResponseRulesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> _repeated_responseRules_codec
        = pb::FieldCodec.ForMessage(18, global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> responseRules_ = new pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule>();
    /// <summary>
    /// The list of rules to apply to responses.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.Rule> ResponseRules {
      get { return responseRules_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!requestRules_.Equals(other.requestRules_)) return false;
      if(!responseRules_.Equals(other.responseRules_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= requestRules_.GetHashCode();
      hash ^= responseRules_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      requestRules_.WriteTo(output, _repeated_requestRules_codec);
      responseRules_.WriteTo(output, _repeated_responseRules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += requestRules_.CalculateSize(_repeated_requestRules_codec);
      size += responseRules_.CalculateSize(_repeated_responseRules_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      requestRules_.Add(other.requestRules_);
      responseRules_.Add(other.responseRules_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            requestRules_.AddEntriesFrom(input, _repeated_requestRules_codec);
            break;
          }
          case 18: {
            responseRules_.AddEntriesFrom(input, _repeated_responseRules_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Config message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ValueType {
        [pbr::OriginalName("STRING")] String = 0,
        [pbr::OriginalName("NUMBER")] Number = 1,
      }

      public sealed partial class KeyValuePair : pb::IMessage<KeyValuePair> {
        private static readonly pb::MessageParser<KeyValuePair> _parser = new pb::MessageParser<KeyValuePair>(() => new KeyValuePair());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<KeyValuePair> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public KeyValuePair() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public KeyValuePair(KeyValuePair other) : this() {
          metadataNamespace_ = other.metadataNamespace_;
          key_ = other.key_;
          value_ = other.value_;
          type_ = other.type_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public KeyValuePair Clone() {
          return new KeyValuePair(this);
        }

        /// <summary>Field number for the "metadata_namespace" field.</summary>
        public const int MetadataNamespaceFieldNumber = 1;
        private string metadataNamespace_ = "";
        /// <summary>
        /// The namespace — if this is empty, the filter's namespace will be used.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string MetadataNamespace {
          get { return metadataNamespace_; }
          set {
            metadataNamespace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "key" field.</summary>
        public const int KeyFieldNumber = 2;
        private string key_ = "";
        /// <summary>
        /// The key to use within the namespace.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Key {
          get { return key_; }
          set {
            key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "value" field.</summary>
        public const int ValueFieldNumber = 3;
        private string value_ = "";
        /// <summary>
        /// The value to pair with the given key.
        ///
        /// When used for a `on_header_present` case, if value is non-empty it'll be used
        /// instead of the header value. If both are empty, no metadata is added.
        ///
        /// When used for a `on_header_missing` case, a non-empty value must be provided
        /// otherwise no metadata is added.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Value {
          get { return value_; }
          set {
            value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 4;
        private global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.ValueType type_ = 0;
        /// <summary>
        /// The value's type — defaults to string.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.ValueType Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as KeyValuePair);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(KeyValuePair other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (MetadataNamespace != other.MetadataNamespace) return false;
          if (Key != other.Key) return false;
          if (Value != other.Value) return false;
          if (Type != other.Type) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (MetadataNamespace.Length != 0) hash ^= MetadataNamespace.GetHashCode();
          if (Key.Length != 0) hash ^= Key.GetHashCode();
          if (Value.Length != 0) hash ^= Value.GetHashCode();
          if (Type != 0) hash ^= Type.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (MetadataNamespace.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(MetadataNamespace);
          }
          if (Key.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Key);
          }
          if (Value.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Value);
          }
          if (Type != 0) {
            output.WriteRawTag(32);
            output.WriteEnum((int) Type);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (MetadataNamespace.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(MetadataNamespace);
          }
          if (Key.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
          }
          if (Value.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
          }
          if (Type != 0) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(KeyValuePair other) {
          if (other == null) {
            return;
          }
          if (other.MetadataNamespace.Length != 0) {
            MetadataNamespace = other.MetadataNamespace;
          }
          if (other.Key.Length != 0) {
            Key = other.Key;
          }
          if (other.Value.Length != 0) {
            Value = other.Value;
          }
          if (other.Type != 0) {
            Type = other.Type;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                MetadataNamespace = input.ReadString();
                break;
              }
              case 18: {
                Key = input.ReadString();
                break;
              }
              case 26: {
                Value = input.ReadString();
                break;
              }
              case 32: {
                type_ = (global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.ValueType) input.ReadEnum();
                break;
              }
            }
          }
        }

      }

      /// <summary>
      /// A Rule defines what metadata to apply when a header is present or missing.
      /// </summary>
      public sealed partial class Rule : pb::IMessage<Rule> {
        private static readonly pb::MessageParser<Rule> _parser = new pb::MessageParser<Rule>(() => new Rule());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Rule> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Rule() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Rule(Rule other) : this() {
          header_ = other.header_;
          OnHeaderPresent = other.onHeaderPresent_ != null ? other.OnHeaderPresent.Clone() : null;
          OnHeaderMissing = other.onHeaderMissing_ != null ? other.OnHeaderMissing.Clone() : null;
          remove_ = other.remove_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Rule Clone() {
          return new Rule(this);
        }

        /// <summary>Field number for the "header" field.</summary>
        public const int HeaderFieldNumber = 1;
        private string header_ = "";
        /// <summary>
        /// The header that triggers this rule — required.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Header {
          get { return header_; }
          set {
            header_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "on_header_present" field.</summary>
        public const int OnHeaderPresentFieldNumber = 2;
        private global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair onHeaderPresent_;
        /// <summary>
        /// If the header is present, apply this metadata KeyValuePair.
        ///
        /// If the value in the KeyValuePair is non-empty, it'll be used instead
        /// of the header value.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair OnHeaderPresent {
          get { return onHeaderPresent_; }
          set {
            onHeaderPresent_ = value;
          }
        }

        /// <summary>Field number for the "on_header_missing" field.</summary>
        public const int OnHeaderMissingFieldNumber = 3;
        private global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair onHeaderMissing_;
        /// <summary>
        /// If the header is not present, apply this metadata KeyValuePair.
        ///
        /// The value in the KeyValuePair must be set, since it'll be used in lieu
        /// of the missing header value.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair OnHeaderMissing {
          get { return onHeaderMissing_; }
          set {
            onHeaderMissing_ = value;
          }
        }

        /// <summary>Field number for the "remove" field.</summary>
        public const int RemoveFieldNumber = 4;
        private bool remove_;
        /// <summary>
        /// Whether or not to remove the header after a rule is applied.
        ///
        /// This prevents headers from leaking.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Remove {
          get { return remove_; }
          set {
            remove_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Rule);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Rule other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Header != other.Header) return false;
          if (!object.Equals(OnHeaderPresent, other.OnHeaderPresent)) return false;
          if (!object.Equals(OnHeaderMissing, other.OnHeaderMissing)) return false;
          if (Remove != other.Remove) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Header.Length != 0) hash ^= Header.GetHashCode();
          if (onHeaderPresent_ != null) hash ^= OnHeaderPresent.GetHashCode();
          if (onHeaderMissing_ != null) hash ^= OnHeaderMissing.GetHashCode();
          if (Remove != false) hash ^= Remove.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Header.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Header);
          }
          if (onHeaderPresent_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(OnHeaderPresent);
          }
          if (onHeaderMissing_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(OnHeaderMissing);
          }
          if (Remove != false) {
            output.WriteRawTag(32);
            output.WriteBool(Remove);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Header.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Header);
          }
          if (onHeaderPresent_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnHeaderPresent);
          }
          if (onHeaderMissing_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnHeaderMissing);
          }
          if (Remove != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Rule other) {
          if (other == null) {
            return;
          }
          if (other.Header.Length != 0) {
            Header = other.Header;
          }
          if (other.onHeaderPresent_ != null) {
            if (onHeaderPresent_ == null) {
              onHeaderPresent_ = new global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair();
            }
            OnHeaderPresent.MergeFrom(other.OnHeaderPresent);
          }
          if (other.onHeaderMissing_ != null) {
            if (onHeaderMissing_ == null) {
              onHeaderMissing_ = new global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair();
            }
            OnHeaderMissing.MergeFrom(other.OnHeaderMissing);
          }
          if (other.Remove != false) {
            Remove = other.Remove;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Header = input.ReadString();
                break;
              }
              case 18: {
                if (onHeaderPresent_ == null) {
                  onHeaderPresent_ = new global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair();
                }
                input.ReadMessage(onHeaderPresent_);
                break;
              }
              case 26: {
                if (onHeaderMissing_ == null) {
                  onHeaderMissing_ = new global::Envoy.Config.Filter.Http.HeaderToMetadata.V2.Config.Types.KeyValuePair();
                }
                input.ReadMessage(onHeaderMissing_);
                break;
              }
              case 32: {
                Remove = input.ReadBool();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
