// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envoy/api/v2/core/grpc_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Api.V2.Core {

  /// <summary>Holder for reflection information generated from envoy/api/v2/core/grpc_service.proto</summary>
  public static partial class GrpcServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for envoy/api/v2/core/grpc_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRlbnZveS9hcGkvdjIvY29yZS9ncnBjX3NlcnZpY2UucHJvdG8SEWVudm95",
            "LmFwaS52Mi5jb3JlGhxlbnZveS9hcGkvdjIvY29yZS9iYXNlLnByb3RvGh5n",
            "b29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8aHGdvb2dsZS9wcm90b2J1",
            "Zi9zdHJ1Y3QucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoX",
            "dmFsaWRhdGUvdmFsaWRhdGUucHJvdG8aFGdvZ29wcm90by9nb2dvLnByb3Rv",
            "IvcNCgtHcnBjU2VydmljZRI+CgplbnZveV9ncnBjGAEgASgLMiguZW52b3ku",
            "YXBpLnYyLmNvcmUuR3JwY1NlcnZpY2UuRW52b3lHcnBjSAASQAoLZ29vZ2xl",
            "X2dycGMYAiABKAsyKS5lbnZveS5hcGkudjIuY29yZS5HcnBjU2VydmljZS5H",
            "b29nbGVHcnBjSAASKgoHdGltZW91dBgDIAEoCzIZLmdvb2dsZS5wcm90b2J1",
            "Zi5EdXJhdGlvbhI4ChBpbml0aWFsX21ldGFkYXRhGAUgAygLMh4uZW52b3ku",
            "YXBpLnYyLmNvcmUuSGVhZGVyVmFsdWUaLAoJRW52b3lHcnBjEh8KDGNsdXN0",
            "ZXJfbmFtZRgBIAEoCUIJuunAAwRyAiABGrALCgpHb29nbGVHcnBjEh0KCnRh",
            "cmdldF91cmkYASABKAlCCbrpwAMEcgIgARJZChNjaGFubmVsX2NyZWRlbnRp",
            "YWxzGAIgASgLMjwuZW52b3kuYXBpLnYyLmNvcmUuR3JwY1NlcnZpY2UuR29v",
            "Z2xlR3JwYy5DaGFubmVsQ3JlZGVudGlhbHMSUwoQY2FsbF9jcmVkZW50aWFs",
            "cxgDIAMoCzI5LmVudm95LmFwaS52Mi5jb3JlLkdycGNTZXJ2aWNlLkdvb2ds",
            "ZUdycGMuQ2FsbENyZWRlbnRpYWxzEh4KC3N0YXRfcHJlZml4GAQgASgJQgm6",
            "6cADBHICIAESIAoYY3JlZGVudGlhbHNfZmFjdG9yeV9uYW1lGAUgASgJEicK",
            "BmNvbmZpZxgGIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QaqgEKDlNz",
            "bENyZWRlbnRpYWxzEjEKCnJvb3RfY2VydHMYASABKAsyHS5lbnZveS5hcGku",
            "djIuY29yZS5EYXRhU291cmNlEjIKC3ByaXZhdGVfa2V5GAIgASgLMh0uZW52",
            "b3kuYXBpLnYyLmNvcmUuRGF0YVNvdXJjZRIxCgpjZXJ0X2NoYWluGAMgASgL",
            "Mh0uZW52b3kuYXBpLnYyLmNvcmUuRGF0YVNvdXJjZRq6AQoSQ2hhbm5lbENy",
            "ZWRlbnRpYWxzElMKD3NzbF9jcmVkZW50aWFscxgBIAEoCzI4LmVudm95LmFw",
            "aS52Mi5jb3JlLkdycGNTZXJ2aWNlLkdvb2dsZUdycGMuU3NsQ3JlZGVudGlh",
            "bHNIABIwCg5nb29nbGVfZGVmYXVsdBgCIAEoCzIWLmdvb2dsZS5wcm90b2J1",
            "Zi5FbXB0eUgAQh0KFGNyZWRlbnRpYWxfc3BlY2lmaWVyEgW46cADARr9BQoP",
            "Q2FsbENyZWRlbnRpYWxzEhYKDGFjY2Vzc190b2tlbhgBIAEoCUgAEjcKFWdv",
            "b2dsZV9jb21wdXRlX2VuZ2luZRgCIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eUgAEh4KFGdvb2dsZV9yZWZyZXNoX3Rva2VuGAMgASgJSAASggEKGnNl",
            "cnZpY2VfYWNjb3VudF9qd3RfYWNjZXNzGAQgASgLMlwuZW52b3kuYXBpLnYy",
            "LmNvcmUuR3JwY1NlcnZpY2UuR29vZ2xlR3JwYy5DYWxsQ3JlZGVudGlhbHMu",
            "U2VydmljZUFjY291bnRKV1RBY2Nlc3NDcmVkZW50aWFsc0gAEmQKCmdvb2ds",
            "ZV9pYW0YBSABKAsyTi5lbnZveS5hcGkudjIuY29yZS5HcnBjU2VydmljZS5H",
            "b29nbGVHcnBjLkNhbGxDcmVkZW50aWFscy5Hb29nbGVJQU1DcmVkZW50aWFs",
            "c0gAEm4KC2Zyb21fcGx1Z2luGAYgASgLMlcuZW52b3kuYXBpLnYyLmNvcmUu",
            "R3JwY1NlcnZpY2UuR29vZ2xlR3JwYy5DYWxsQ3JlZGVudGlhbHMuTWV0YWRh",
            "dGFDcmVkZW50aWFsc0Zyb21QbHVnaW5IABpWCiJTZXJ2aWNlQWNjb3VudEpX",
            "VEFjY2Vzc0NyZWRlbnRpYWxzEhAKCGpzb25fa2V5GAEgASgJEh4KFnRva2Vu",
            "X2xpZmV0aW1lX3NlY29uZHMYAiABKAQaTwoUR29vZ2xlSUFNQ3JlZGVudGlh",
            "bHMSGwoTYXV0aG9yaXphdGlvbl90b2tlbhgBIAEoCRIaChJhdXRob3JpdHlf",
            "c2VsZWN0b3IYAiABKAkaVgodTWV0YWRhdGFDcmVkZW50aWFsc0Zyb21QbHVn",
            "aW4SDAoEbmFtZRgBIAEoCRInCgZjb25maWcYAiABKAsyFy5nb29nbGUucHJv",
            "dG9idWYuU3RydWN0Qh0KFGNyZWRlbnRpYWxfc3BlY2lmaWVyEgW46cADAUIZ",
            "ChB0YXJnZXRfc3BlY2lmaWVyEgW46cADAUoECAQQBUIEqOIeAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Api.V2.Core.BaseReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService), global::Envoy.Api.V2.Core.GrpcService.Parser, new[]{ "EnvoyGrpc", "GoogleGrpc", "Timeout", "InitialMetadata" }, new[]{ "TargetSpecifier" }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc), global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc.Parser, new[]{ "ClusterName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Parser, new[]{ "TargetUri", "ChannelCredentials", "CallCredentials", "StatPrefix", "CredentialsFactoryName", "Config" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials.Parser, new[]{ "RootCerts", "PrivateKey", "CertChain" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials.Parser, new[]{ "SslCredentials", "GoogleDefault" }, new[]{ "CredentialSpecifier" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Parser, new[]{ "AccessToken", "GoogleComputeEngine", "GoogleRefreshToken", "ServiceAccountJwtAccess", "GoogleIam", "FromPlugin" }, new[]{ "CredentialSpecifier" }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials.Parser, new[]{ "JsonKey", "TokenLifetimeSeconds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials.Parser, new[]{ "AuthorizationToken", "AuthoritySelector" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin), global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin.Parser, new[]{ "Name", "Config" }, null, null, null)})})})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// gRPC service configuration. This is used by :ref:`ApiConfigSource
  /// &lt;envoy_api_msg_core.ApiConfigSource>` and filter configurations.
  /// </summary>
  public sealed partial class GrpcService : pb::IMessage<GrpcService> {
    private static readonly pb::MessageParser<GrpcService> _parser = new pb::MessageParser<GrpcService>(() => new GrpcService());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcService> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Api.V2.Core.GrpcServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcService() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcService(GrpcService other) : this() {
      Timeout = other.timeout_ != null ? other.Timeout.Clone() : null;
      initialMetadata_ = other.initialMetadata_.Clone();
      switch (other.TargetSpecifierCase) {
        case TargetSpecifierOneofCase.EnvoyGrpc:
          EnvoyGrpc = other.EnvoyGrpc.Clone();
          break;
        case TargetSpecifierOneofCase.GoogleGrpc:
          GoogleGrpc = other.GoogleGrpc.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcService Clone() {
      return new GrpcService(this);
    }

    /// <summary>Field number for the "envoy_grpc" field.</summary>
    public const int EnvoyGrpcFieldNumber = 1;
    /// <summary>
    /// Envoy's in-built gRPC client.
    /// See the :ref:`gRPC services overview &lt;arch_overview_grpc_services>`
    /// documentation for discussion on gRPC client selection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc EnvoyGrpc {
      get { return targetSpecifierCase_ == TargetSpecifierOneofCase.EnvoyGrpc ? (global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc) targetSpecifier_ : null; }
      set {
        targetSpecifier_ = value;
        targetSpecifierCase_ = value == null ? TargetSpecifierOneofCase.None : TargetSpecifierOneofCase.EnvoyGrpc;
      }
    }

    /// <summary>Field number for the "google_grpc" field.</summary>
    public const int GoogleGrpcFieldNumber = 2;
    /// <summary>
    /// `Google C++ gRPC client &lt;https://github.com/grpc/grpc>`_
    /// See the :ref:`gRPC services overview &lt;arch_overview_grpc_services>`
    /// documentation for discussion on gRPC client selection.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc GoogleGrpc {
      get { return targetSpecifierCase_ == TargetSpecifierOneofCase.GoogleGrpc ? (global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc) targetSpecifier_ : null; }
      set {
        targetSpecifier_ = value;
        targetSpecifierCase_ = value == null ? TargetSpecifierOneofCase.None : TargetSpecifierOneofCase.GoogleGrpc;
      }
    }

    /// <summary>Field number for the "timeout" field.</summary>
    public const int TimeoutFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Duration timeout_;
    /// <summary>
    /// The timeout for the gRPC request. This is the timeout for a specific
    /// request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Duration Timeout {
      get { return timeout_; }
      set {
        timeout_ = value;
      }
    }

    /// <summary>Field number for the "initial_metadata" field.</summary>
    public const int InitialMetadataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Envoy.Api.V2.Core.HeaderValue> _repeated_initialMetadata_codec
        = pb::FieldCodec.ForMessage(42, global::Envoy.Api.V2.Core.HeaderValue.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Api.V2.Core.HeaderValue> initialMetadata_ = new pbc::RepeatedField<global::Envoy.Api.V2.Core.HeaderValue>();
    /// <summary>
    /// Additional metadata to include in streams initiated to the GrpcService.
    /// This can be used for scenarios in which additional ad hoc authorization
    /// headers (e.g. `x-foo-bar: baz-key`) are to be injected.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Api.V2.Core.HeaderValue> InitialMetadata {
      get { return initialMetadata_; }
    }

    private object targetSpecifier_;
    /// <summary>Enum of possible cases for the "target_specifier" oneof.</summary>
    public enum TargetSpecifierOneofCase {
      None = 0,
      EnvoyGrpc = 1,
      GoogleGrpc = 2,
    }
    private TargetSpecifierOneofCase targetSpecifierCase_ = TargetSpecifierOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TargetSpecifierOneofCase TargetSpecifierCase {
      get { return targetSpecifierCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTargetSpecifier() {
      targetSpecifierCase_ = TargetSpecifierOneofCase.None;
      targetSpecifier_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcService);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcService other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EnvoyGrpc, other.EnvoyGrpc)) return false;
      if (!object.Equals(GoogleGrpc, other.GoogleGrpc)) return false;
      if (!object.Equals(Timeout, other.Timeout)) return false;
      if(!initialMetadata_.Equals(other.initialMetadata_)) return false;
      if (TargetSpecifierCase != other.TargetSpecifierCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.EnvoyGrpc) hash ^= EnvoyGrpc.GetHashCode();
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.GoogleGrpc) hash ^= GoogleGrpc.GetHashCode();
      if (timeout_ != null) hash ^= Timeout.GetHashCode();
      hash ^= initialMetadata_.GetHashCode();
      hash ^= (int) targetSpecifierCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.EnvoyGrpc) {
        output.WriteRawTag(10);
        output.WriteMessage(EnvoyGrpc);
      }
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.GoogleGrpc) {
        output.WriteRawTag(18);
        output.WriteMessage(GoogleGrpc);
      }
      if (timeout_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Timeout);
      }
      initialMetadata_.WriteTo(output, _repeated_initialMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.EnvoyGrpc) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnvoyGrpc);
      }
      if (targetSpecifierCase_ == TargetSpecifierOneofCase.GoogleGrpc) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleGrpc);
      }
      if (timeout_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timeout);
      }
      size += initialMetadata_.CalculateSize(_repeated_initialMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcService other) {
      if (other == null) {
        return;
      }
      if (other.timeout_ != null) {
        if (timeout_ == null) {
          timeout_ = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        Timeout.MergeFrom(other.Timeout);
      }
      initialMetadata_.Add(other.initialMetadata_);
      switch (other.TargetSpecifierCase) {
        case TargetSpecifierOneofCase.EnvoyGrpc:
          if (EnvoyGrpc == null) {
            EnvoyGrpc = new global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc();
          }
          EnvoyGrpc.MergeFrom(other.EnvoyGrpc);
          break;
        case TargetSpecifierOneofCase.GoogleGrpc:
          if (GoogleGrpc == null) {
            GoogleGrpc = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc();
          }
          GoogleGrpc.MergeFrom(other.GoogleGrpc);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.EnvoyGrpc();
            if (targetSpecifierCase_ == TargetSpecifierOneofCase.EnvoyGrpc) {
              subBuilder.MergeFrom(EnvoyGrpc);
            }
            input.ReadMessage(subBuilder);
            EnvoyGrpc = subBuilder;
            break;
          }
          case 18: {
            global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc();
            if (targetSpecifierCase_ == TargetSpecifierOneofCase.GoogleGrpc) {
              subBuilder.MergeFrom(GoogleGrpc);
            }
            input.ReadMessage(subBuilder);
            GoogleGrpc = subBuilder;
            break;
          }
          case 26: {
            if (timeout_ == null) {
              timeout_ = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(timeout_);
            break;
          }
          case 42: {
            initialMetadata_.AddEntriesFrom(input, _repeated_initialMetadata_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GrpcService message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class EnvoyGrpc : pb::IMessage<EnvoyGrpc> {
        private static readonly pb::MessageParser<EnvoyGrpc> _parser = new pb::MessageParser<EnvoyGrpc>(() => new EnvoyGrpc());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<EnvoyGrpc> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Api.V2.Core.GrpcService.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EnvoyGrpc() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EnvoyGrpc(EnvoyGrpc other) : this() {
          clusterName_ = other.clusterName_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EnvoyGrpc Clone() {
          return new EnvoyGrpc(this);
        }

        /// <summary>Field number for the "cluster_name" field.</summary>
        public const int ClusterNameFieldNumber = 1;
        private string clusterName_ = "";
        /// <summary>
        /// The name of the upstream gRPC cluster. SSL credentials will be supplied
        /// in the :ref:`Cluster &lt;envoy_api_msg_Cluster>` :ref:`tls_context
        /// &lt;envoy_api_field_Cluster.tls_context>`.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ClusterName {
          get { return clusterName_; }
          set {
            clusterName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as EnvoyGrpc);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(EnvoyGrpc other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ClusterName != other.ClusterName) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (ClusterName.Length != 0) hash ^= ClusterName.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (ClusterName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ClusterName);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (ClusterName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ClusterName);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(EnvoyGrpc other) {
          if (other == null) {
            return;
          }
          if (other.ClusterName.Length != 0) {
            ClusterName = other.ClusterName;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ClusterName = input.ReadString();
                break;
              }
            }
          }
        }

      }

      /// <summary>
      /// [#proto-status: draft]
      /// </summary>
      public sealed partial class GoogleGrpc : pb::IMessage<GoogleGrpc> {
        private static readonly pb::MessageParser<GoogleGrpc> _parser = new pb::MessageParser<GoogleGrpc>(() => new GoogleGrpc());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<GoogleGrpc> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Api.V2.Core.GrpcService.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GoogleGrpc() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GoogleGrpc(GoogleGrpc other) : this() {
          targetUri_ = other.targetUri_;
          ChannelCredentials = other.channelCredentials_ != null ? other.ChannelCredentials.Clone() : null;
          callCredentials_ = other.callCredentials_.Clone();
          statPrefix_ = other.statPrefix_;
          credentialsFactoryName_ = other.credentialsFactoryName_;
          Config = other.config_ != null ? other.Config.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GoogleGrpc Clone() {
          return new GoogleGrpc(this);
        }

        /// <summary>Field number for the "target_uri" field.</summary>
        public const int TargetUriFieldNumber = 1;
        private string targetUri_ = "";
        /// <summary>
        /// The target URI when using the `Google C++ gRPC client
        /// &lt;https://github.com/grpc/grpc>`_. SSL credentials will be supplied in
        /// :ref:`channel_credentials &lt;envoy_api_field_core.GrpcService.GoogleGrpc.channel_credentials>`.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string TargetUri {
          get { return targetUri_; }
          set {
            targetUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "channel_credentials" field.</summary>
        public const int ChannelCredentialsFieldNumber = 2;
        private global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials channelCredentials_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials ChannelCredentials {
          get { return channelCredentials_; }
          set {
            channelCredentials_ = value;
          }
        }

        /// <summary>Field number for the "call_credentials" field.</summary>
        public const int CallCredentialsFieldNumber = 3;
        private static readonly pb::FieldCodec<global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials> _repeated_callCredentials_codec
            = pb::FieldCodec.ForMessage(26, global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Parser);
        private readonly pbc::RepeatedField<global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials> callCredentials_ = new pbc::RepeatedField<global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials>();
        /// <summary>
        /// A set of call credentials that can be composed with `channel credentials
        /// &lt;https://grpc.io/docs/guides/auth.html#credential-types>`_.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials> CallCredentials {
          get { return callCredentials_; }
        }

        /// <summary>Field number for the "stat_prefix" field.</summary>
        public const int StatPrefixFieldNumber = 4;
        private string statPrefix_ = "";
        /// <summary>
        /// The human readable prefix to use when emitting statistics for the gRPC
        /// service.
        ///
        /// .. csv-table::
        ///    :header: Name, Type, Description
        ///    :widths: 1, 1, 2
        ///
        ///    streams_total, Counter, Total number of streams opened
        ///    streams_closed_&lt;gRPC status code>, Counter, Total streams closed with &lt;gRPC status code>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string StatPrefix {
          get { return statPrefix_; }
          set {
            statPrefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "credentials_factory_name" field.</summary>
        public const int CredentialsFactoryNameFieldNumber = 5;
        private string credentialsFactoryName_ = "";
        /// <summary>
        /// The name of the Google gRPC credentials factory to use. This must have been registered with
        /// Envoy. If this is empty, a default credentials factory will be used that sets up channel
        /// credentials based on other configuration parameters.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string CredentialsFactoryName {
          get { return credentialsFactoryName_; }
          set {
            credentialsFactoryName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "config" field.</summary>
        public const int ConfigFieldNumber = 6;
        private global::Google.Protobuf.WellKnownTypes.Struct config_;
        /// <summary>
        /// Additional configuration for site-specific customizations of the Google
        /// gRPC library.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Protobuf.WellKnownTypes.Struct Config {
          get { return config_; }
          set {
            config_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as GoogleGrpc);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(GoogleGrpc other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (TargetUri != other.TargetUri) return false;
          if (!object.Equals(ChannelCredentials, other.ChannelCredentials)) return false;
          if(!callCredentials_.Equals(other.callCredentials_)) return false;
          if (StatPrefix != other.StatPrefix) return false;
          if (CredentialsFactoryName != other.CredentialsFactoryName) return false;
          if (!object.Equals(Config, other.Config)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (TargetUri.Length != 0) hash ^= TargetUri.GetHashCode();
          if (channelCredentials_ != null) hash ^= ChannelCredentials.GetHashCode();
          hash ^= callCredentials_.GetHashCode();
          if (StatPrefix.Length != 0) hash ^= StatPrefix.GetHashCode();
          if (CredentialsFactoryName.Length != 0) hash ^= CredentialsFactoryName.GetHashCode();
          if (config_ != null) hash ^= Config.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (TargetUri.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(TargetUri);
          }
          if (channelCredentials_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(ChannelCredentials);
          }
          callCredentials_.WriteTo(output, _repeated_callCredentials_codec);
          if (StatPrefix.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(StatPrefix);
          }
          if (CredentialsFactoryName.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(CredentialsFactoryName);
          }
          if (config_ != null) {
            output.WriteRawTag(50);
            output.WriteMessage(Config);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (TargetUri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetUri);
          }
          if (channelCredentials_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChannelCredentials);
          }
          size += callCredentials_.CalculateSize(_repeated_callCredentials_codec);
          if (StatPrefix.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(StatPrefix);
          }
          if (CredentialsFactoryName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CredentialsFactoryName);
          }
          if (config_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(GoogleGrpc other) {
          if (other == null) {
            return;
          }
          if (other.TargetUri.Length != 0) {
            TargetUri = other.TargetUri;
          }
          if (other.channelCredentials_ != null) {
            if (channelCredentials_ == null) {
              channelCredentials_ = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials();
            }
            ChannelCredentials.MergeFrom(other.ChannelCredentials);
          }
          callCredentials_.Add(other.callCredentials_);
          if (other.StatPrefix.Length != 0) {
            StatPrefix = other.StatPrefix;
          }
          if (other.CredentialsFactoryName.Length != 0) {
            CredentialsFactoryName = other.CredentialsFactoryName;
          }
          if (other.config_ != null) {
            if (config_ == null) {
              config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            Config.MergeFrom(other.Config);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                TargetUri = input.ReadString();
                break;
              }
              case 18: {
                if (channelCredentials_ == null) {
                  channelCredentials_ = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.ChannelCredentials();
                }
                input.ReadMessage(channelCredentials_);
                break;
              }
              case 26: {
                callCredentials_.AddEntriesFrom(input, _repeated_callCredentials_codec);
                break;
              }
              case 34: {
                StatPrefix = input.ReadString();
                break;
              }
              case 42: {
                CredentialsFactoryName = input.ReadString();
                break;
              }
              case 50: {
                if (config_ == null) {
                  config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
                }
                input.ReadMessage(config_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the GoogleGrpc message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          /// <summary>
          /// See https://grpc.io/grpc/cpp/structgrpc_1_1_ssl_credentials_options.html.
          /// </summary>
          public sealed partial class SslCredentials : pb::IMessage<SslCredentials> {
            private static readonly pb::MessageParser<SslCredentials> _parser = new pb::MessageParser<SslCredentials>(() => new SslCredentials());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<SslCredentials> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public SslCredentials() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public SslCredentials(SslCredentials other) : this() {
              RootCerts = other.rootCerts_ != null ? other.RootCerts.Clone() : null;
              PrivateKey = other.privateKey_ != null ? other.PrivateKey.Clone() : null;
              CertChain = other.certChain_ != null ? other.CertChain.Clone() : null;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public SslCredentials Clone() {
              return new SslCredentials(this);
            }

            /// <summary>Field number for the "root_certs" field.</summary>
            public const int RootCertsFieldNumber = 1;
            private global::Envoy.Api.V2.Core.DataSource rootCerts_;
            /// <summary>
            /// PEM encoded server root certificates.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.DataSource RootCerts {
              get { return rootCerts_; }
              set {
                rootCerts_ = value;
              }
            }

            /// <summary>Field number for the "private_key" field.</summary>
            public const int PrivateKeyFieldNumber = 2;
            private global::Envoy.Api.V2.Core.DataSource privateKey_;
            /// <summary>
            /// PEM encoded client private key.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.DataSource PrivateKey {
              get { return privateKey_; }
              set {
                privateKey_ = value;
              }
            }

            /// <summary>Field number for the "cert_chain" field.</summary>
            public const int CertChainFieldNumber = 3;
            private global::Envoy.Api.V2.Core.DataSource certChain_;
            /// <summary>
            /// PEM encoded client certificate chain.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.DataSource CertChain {
              get { return certChain_; }
              set {
                certChain_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as SslCredentials);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(SslCredentials other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!object.Equals(RootCerts, other.RootCerts)) return false;
              if (!object.Equals(PrivateKey, other.PrivateKey)) return false;
              if (!object.Equals(CertChain, other.CertChain)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (rootCerts_ != null) hash ^= RootCerts.GetHashCode();
              if (privateKey_ != null) hash ^= PrivateKey.GetHashCode();
              if (certChain_ != null) hash ^= CertChain.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (rootCerts_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(RootCerts);
              }
              if (privateKey_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(PrivateKey);
              }
              if (certChain_ != null) {
                output.WriteRawTag(26);
                output.WriteMessage(CertChain);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (rootCerts_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(RootCerts);
              }
              if (privateKey_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrivateKey);
              }
              if (certChain_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(CertChain);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(SslCredentials other) {
              if (other == null) {
                return;
              }
              if (other.rootCerts_ != null) {
                if (rootCerts_ == null) {
                  rootCerts_ = new global::Envoy.Api.V2.Core.DataSource();
                }
                RootCerts.MergeFrom(other.RootCerts);
              }
              if (other.privateKey_ != null) {
                if (privateKey_ == null) {
                  privateKey_ = new global::Envoy.Api.V2.Core.DataSource();
                }
                PrivateKey.MergeFrom(other.PrivateKey);
              }
              if (other.certChain_ != null) {
                if (certChain_ == null) {
                  certChain_ = new global::Envoy.Api.V2.Core.DataSource();
                }
                CertChain.MergeFrom(other.CertChain);
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    if (rootCerts_ == null) {
                      rootCerts_ = new global::Envoy.Api.V2.Core.DataSource();
                    }
                    input.ReadMessage(rootCerts_);
                    break;
                  }
                  case 18: {
                    if (privateKey_ == null) {
                      privateKey_ = new global::Envoy.Api.V2.Core.DataSource();
                    }
                    input.ReadMessage(privateKey_);
                    break;
                  }
                  case 26: {
                    if (certChain_ == null) {
                      certChain_ = new global::Envoy.Api.V2.Core.DataSource();
                    }
                    input.ReadMessage(certChain_);
                    break;
                  }
                }
              }
            }

          }

          /// <summary>
          /// See https://grpc.io/docs/guides/auth.html#credential-types to understand Channel and Call
          /// credential types.
          /// </summary>
          public sealed partial class ChannelCredentials : pb::IMessage<ChannelCredentials> {
            private static readonly pb::MessageParser<ChannelCredentials> _parser = new pb::MessageParser<ChannelCredentials>(() => new ChannelCredentials());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<ChannelCredentials> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public ChannelCredentials() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public ChannelCredentials(ChannelCredentials other) : this() {
              switch (other.CredentialSpecifierCase) {
                case CredentialSpecifierOneofCase.SslCredentials:
                  SslCredentials = other.SslCredentials.Clone();
                  break;
                case CredentialSpecifierOneofCase.GoogleDefault:
                  GoogleDefault = other.GoogleDefault.Clone();
                  break;
              }

              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public ChannelCredentials Clone() {
              return new ChannelCredentials(this);
            }

            /// <summary>Field number for the "ssl_credentials" field.</summary>
            public const int SslCredentialsFieldNumber = 1;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials SslCredentials {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.SslCredentials ? (global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.SslCredentials;
              }
            }

            /// <summary>Field number for the "google_default" field.</summary>
            public const int GoogleDefaultFieldNumber = 2;
            /// <summary>
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a6beb3ac70ff94bd2ebbd89b8f21d1f61
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Google.Protobuf.WellKnownTypes.Empty GoogleDefault {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleDefault ? (global::Google.Protobuf.WellKnownTypes.Empty) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.GoogleDefault;
              }
            }

            private object credentialSpecifier_;
            /// <summary>Enum of possible cases for the "credential_specifier" oneof.</summary>
            public enum CredentialSpecifierOneofCase {
              None = 0,
              SslCredentials = 1,
              GoogleDefault = 2,
            }
            private CredentialSpecifierOneofCase credentialSpecifierCase_ = CredentialSpecifierOneofCase.None;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public CredentialSpecifierOneofCase CredentialSpecifierCase {
              get { return credentialSpecifierCase_; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void ClearCredentialSpecifier() {
              credentialSpecifierCase_ = CredentialSpecifierOneofCase.None;
              credentialSpecifier_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as ChannelCredentials);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(ChannelCredentials other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!object.Equals(SslCredentials, other.SslCredentials)) return false;
              if (!object.Equals(GoogleDefault, other.GoogleDefault)) return false;
              if (CredentialSpecifierCase != other.CredentialSpecifierCase) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.SslCredentials) hash ^= SslCredentials.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleDefault) hash ^= GoogleDefault.GetHashCode();
              hash ^= (int) credentialSpecifierCase_;
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.SslCredentials) {
                output.WriteRawTag(10);
                output.WriteMessage(SslCredentials);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleDefault) {
                output.WriteRawTag(18);
                output.WriteMessage(GoogleDefault);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.SslCredentials) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(SslCredentials);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleDefault) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleDefault);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(ChannelCredentials other) {
              if (other == null) {
                return;
              }
              switch (other.CredentialSpecifierCase) {
                case CredentialSpecifierOneofCase.SslCredentials:
                  if (SslCredentials == null) {
                    SslCredentials = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials();
                  }
                  SslCredentials.MergeFrom(other.SslCredentials);
                  break;
                case CredentialSpecifierOneofCase.GoogleDefault:
                  if (GoogleDefault == null) {
                    GoogleDefault = new global::Google.Protobuf.WellKnownTypes.Empty();
                  }
                  GoogleDefault.MergeFrom(other.GoogleDefault);
                  break;
              }

              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.SslCredentials();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.SslCredentials) {
                      subBuilder.MergeFrom(SslCredentials);
                    }
                    input.ReadMessage(subBuilder);
                    SslCredentials = subBuilder;
                    break;
                  }
                  case 18: {
                    global::Google.Protobuf.WellKnownTypes.Empty subBuilder = new global::Google.Protobuf.WellKnownTypes.Empty();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleDefault) {
                      subBuilder.MergeFrom(GoogleDefault);
                    }
                    input.ReadMessage(subBuilder);
                    GoogleDefault = subBuilder;
                    break;
                  }
                }
              }
            }

          }

          public sealed partial class CallCredentials : pb::IMessage<CallCredentials> {
            private static readonly pb::MessageParser<CallCredentials> _parser = new pb::MessageParser<CallCredentials>(() => new CallCredentials());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<CallCredentials> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Descriptor.NestedTypes[2]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public CallCredentials() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public CallCredentials(CallCredentials other) : this() {
              switch (other.CredentialSpecifierCase) {
                case CredentialSpecifierOneofCase.AccessToken:
                  AccessToken = other.AccessToken;
                  break;
                case CredentialSpecifierOneofCase.GoogleComputeEngine:
                  GoogleComputeEngine = other.GoogleComputeEngine.Clone();
                  break;
                case CredentialSpecifierOneofCase.GoogleRefreshToken:
                  GoogleRefreshToken = other.GoogleRefreshToken;
                  break;
                case CredentialSpecifierOneofCase.ServiceAccountJwtAccess:
                  ServiceAccountJwtAccess = other.ServiceAccountJwtAccess.Clone();
                  break;
                case CredentialSpecifierOneofCase.GoogleIam:
                  GoogleIam = other.GoogleIam.Clone();
                  break;
                case CredentialSpecifierOneofCase.FromPlugin:
                  FromPlugin = other.FromPlugin.Clone();
                  break;
              }

              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public CallCredentials Clone() {
              return new CallCredentials(this);
            }

            /// <summary>Field number for the "access_token" field.</summary>
            public const int AccessTokenFieldNumber = 1;
            /// <summary>
            /// Access token credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#ad3a80da696ffdaea943f0f858d7a360d.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string AccessToken {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.AccessToken ? (string) credentialSpecifier_ : ""; }
              set {
                credentialSpecifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                credentialSpecifierCase_ = CredentialSpecifierOneofCase.AccessToken;
              }
            }

            /// <summary>Field number for the "google_compute_engine" field.</summary>
            public const int GoogleComputeEngineFieldNumber = 2;
            /// <summary>
            /// Google Compute Engine credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a6beb3ac70ff94bd2ebbd89b8f21d1f61
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Google.Protobuf.WellKnownTypes.Empty GoogleComputeEngine {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleComputeEngine ? (global::Google.Protobuf.WellKnownTypes.Empty) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.GoogleComputeEngine;
              }
            }

            /// <summary>Field number for the "google_refresh_token" field.</summary>
            public const int GoogleRefreshTokenFieldNumber = 3;
            /// <summary>
            /// Google refresh token credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a96901c997b91bc6513b08491e0dca37c.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string GoogleRefreshToken {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleRefreshToken ? (string) credentialSpecifier_ : ""; }
              set {
                credentialSpecifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                credentialSpecifierCase_ = CredentialSpecifierOneofCase.GoogleRefreshToken;
              }
            }

            /// <summary>Field number for the "service_account_jwt_access" field.</summary>
            public const int ServiceAccountJwtAccessFieldNumber = 4;
            /// <summary>
            /// Service Account JWT Access credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a92a9f959d6102461f66ee973d8e9d3aa.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials ServiceAccountJwtAccess {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.ServiceAccountJwtAccess ? (global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.ServiceAccountJwtAccess;
              }
            }

            /// <summary>Field number for the "google_iam" field.</summary>
            public const int GoogleIamFieldNumber = 5;
            /// <summary>
            /// Google IAM credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a9fc1fc101b41e680d47028166e76f9d0.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials GoogleIam {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleIam ? (global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.GoogleIam;
              }
            }

            /// <summary>Field number for the "from_plugin" field.</summary>
            public const int FromPluginFieldNumber = 6;
            /// <summary>
            /// Custom authenticator credentials.
            /// https://grpc.io/grpc/cpp/namespacegrpc.html#a823c6a4b19ffc71fb33e90154ee2ad07.
            /// https://grpc.io/docs/guides/auth.html#extending-grpc-to-support-other-authentication-mechanisms.
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin FromPlugin {
              get { return credentialSpecifierCase_ == CredentialSpecifierOneofCase.FromPlugin ? (global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin) credentialSpecifier_ : null; }
              set {
                credentialSpecifier_ = value;
                credentialSpecifierCase_ = value == null ? CredentialSpecifierOneofCase.None : CredentialSpecifierOneofCase.FromPlugin;
              }
            }

            private object credentialSpecifier_;
            /// <summary>Enum of possible cases for the "credential_specifier" oneof.</summary>
            public enum CredentialSpecifierOneofCase {
              None = 0,
              AccessToken = 1,
              GoogleComputeEngine = 2,
              GoogleRefreshToken = 3,
              ServiceAccountJwtAccess = 4,
              GoogleIam = 5,
              FromPlugin = 6,
            }
            private CredentialSpecifierOneofCase credentialSpecifierCase_ = CredentialSpecifierOneofCase.None;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public CredentialSpecifierOneofCase CredentialSpecifierCase {
              get { return credentialSpecifierCase_; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void ClearCredentialSpecifier() {
              credentialSpecifierCase_ = CredentialSpecifierOneofCase.None;
              credentialSpecifier_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as CallCredentials);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(CallCredentials other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (AccessToken != other.AccessToken) return false;
              if (!object.Equals(GoogleComputeEngine, other.GoogleComputeEngine)) return false;
              if (GoogleRefreshToken != other.GoogleRefreshToken) return false;
              if (!object.Equals(ServiceAccountJwtAccess, other.ServiceAccountJwtAccess)) return false;
              if (!object.Equals(GoogleIam, other.GoogleIam)) return false;
              if (!object.Equals(FromPlugin, other.FromPlugin)) return false;
              if (CredentialSpecifierCase != other.CredentialSpecifierCase) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.AccessToken) hash ^= AccessToken.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleComputeEngine) hash ^= GoogleComputeEngine.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleRefreshToken) hash ^= GoogleRefreshToken.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.ServiceAccountJwtAccess) hash ^= ServiceAccountJwtAccess.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleIam) hash ^= GoogleIam.GetHashCode();
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.FromPlugin) hash ^= FromPlugin.GetHashCode();
              hash ^= (int) credentialSpecifierCase_;
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.AccessToken) {
                output.WriteRawTag(10);
                output.WriteString(AccessToken);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleComputeEngine) {
                output.WriteRawTag(18);
                output.WriteMessage(GoogleComputeEngine);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleRefreshToken) {
                output.WriteRawTag(26);
                output.WriteString(GoogleRefreshToken);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.ServiceAccountJwtAccess) {
                output.WriteRawTag(34);
                output.WriteMessage(ServiceAccountJwtAccess);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleIam) {
                output.WriteRawTag(42);
                output.WriteMessage(GoogleIam);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.FromPlugin) {
                output.WriteRawTag(50);
                output.WriteMessage(FromPlugin);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.AccessToken) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleComputeEngine) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleComputeEngine);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleRefreshToken) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(GoogleRefreshToken);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.ServiceAccountJwtAccess) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServiceAccountJwtAccess);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleIam) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleIam);
              }
              if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.FromPlugin) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(FromPlugin);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(CallCredentials other) {
              if (other == null) {
                return;
              }
              switch (other.CredentialSpecifierCase) {
                case CredentialSpecifierOneofCase.AccessToken:
                  AccessToken = other.AccessToken;
                  break;
                case CredentialSpecifierOneofCase.GoogleComputeEngine:
                  if (GoogleComputeEngine == null) {
                    GoogleComputeEngine = new global::Google.Protobuf.WellKnownTypes.Empty();
                  }
                  GoogleComputeEngine.MergeFrom(other.GoogleComputeEngine);
                  break;
                case CredentialSpecifierOneofCase.GoogleRefreshToken:
                  GoogleRefreshToken = other.GoogleRefreshToken;
                  break;
                case CredentialSpecifierOneofCase.ServiceAccountJwtAccess:
                  if (ServiceAccountJwtAccess == null) {
                    ServiceAccountJwtAccess = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials();
                  }
                  ServiceAccountJwtAccess.MergeFrom(other.ServiceAccountJwtAccess);
                  break;
                case CredentialSpecifierOneofCase.GoogleIam:
                  if (GoogleIam == null) {
                    GoogleIam = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials();
                  }
                  GoogleIam.MergeFrom(other.GoogleIam);
                  break;
                case CredentialSpecifierOneofCase.FromPlugin:
                  if (FromPlugin == null) {
                    FromPlugin = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin();
                  }
                  FromPlugin.MergeFrom(other.FromPlugin);
                  break;
              }

              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    AccessToken = input.ReadString();
                    break;
                  }
                  case 18: {
                    global::Google.Protobuf.WellKnownTypes.Empty subBuilder = new global::Google.Protobuf.WellKnownTypes.Empty();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleComputeEngine) {
                      subBuilder.MergeFrom(GoogleComputeEngine);
                    }
                    input.ReadMessage(subBuilder);
                    GoogleComputeEngine = subBuilder;
                    break;
                  }
                  case 26: {
                    GoogleRefreshToken = input.ReadString();
                    break;
                  }
                  case 34: {
                    global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.ServiceAccountJWTAccessCredentials();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.ServiceAccountJwtAccess) {
                      subBuilder.MergeFrom(ServiceAccountJwtAccess);
                    }
                    input.ReadMessage(subBuilder);
                    ServiceAccountJwtAccess = subBuilder;
                    break;
                  }
                  case 42: {
                    global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.GoogleIAMCredentials();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.GoogleIam) {
                      subBuilder.MergeFrom(GoogleIam);
                    }
                    input.ReadMessage(subBuilder);
                    GoogleIam = subBuilder;
                    break;
                  }
                  case 50: {
                    global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin subBuilder = new global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Types.MetadataCredentialsFromPlugin();
                    if (credentialSpecifierCase_ == CredentialSpecifierOneofCase.FromPlugin) {
                      subBuilder.MergeFrom(FromPlugin);
                    }
                    input.ReadMessage(subBuilder);
                    FromPlugin = subBuilder;
                    break;
                  }
                }
              }
            }

            #region Nested types
            /// <summary>Container for nested types declared in the CallCredentials message type.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static partial class Types {
              public sealed partial class ServiceAccountJWTAccessCredentials : pb::IMessage<ServiceAccountJWTAccessCredentials> {
                private static readonly pb::MessageParser<ServiceAccountJWTAccessCredentials> _parser = new pb::MessageParser<ServiceAccountJWTAccessCredentials>(() => new ServiceAccountJWTAccessCredentials());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<ServiceAccountJWTAccessCredentials> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public ServiceAccountJWTAccessCredentials() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public ServiceAccountJWTAccessCredentials(ServiceAccountJWTAccessCredentials other) : this() {
                  jsonKey_ = other.jsonKey_;
                  tokenLifetimeSeconds_ = other.tokenLifetimeSeconds_;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public ServiceAccountJWTAccessCredentials Clone() {
                  return new ServiceAccountJWTAccessCredentials(this);
                }

                /// <summary>Field number for the "json_key" field.</summary>
                public const int JsonKeyFieldNumber = 1;
                private string jsonKey_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string JsonKey {
                  get { return jsonKey_; }
                  set {
                    jsonKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "token_lifetime_seconds" field.</summary>
                public const int TokenLifetimeSecondsFieldNumber = 2;
                private ulong tokenLifetimeSeconds_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public ulong TokenLifetimeSeconds {
                  get { return tokenLifetimeSeconds_; }
                  set {
                    tokenLifetimeSeconds_ = value;
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other) {
                  return Equals(other as ServiceAccountJWTAccessCredentials);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(ServiceAccountJWTAccessCredentials other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (JsonKey != other.JsonKey) return false;
                  if (TokenLifetimeSeconds != other.TokenLifetimeSeconds) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode() {
                  int hash = 1;
                  if (JsonKey.Length != 0) hash ^= JsonKey.GetHashCode();
                  if (TokenLifetimeSeconds != 0UL) hash ^= TokenLifetimeSeconds.GetHashCode();
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output) {
                  if (JsonKey.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(JsonKey);
                  }
                  if (TokenLifetimeSeconds != 0UL) {
                    output.WriteRawTag(16);
                    output.WriteUInt64(TokenLifetimeSeconds);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize() {
                  int size = 0;
                  if (JsonKey.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(JsonKey);
                  }
                  if (TokenLifetimeSeconds != 0UL) {
                    size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TokenLifetimeSeconds);
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(ServiceAccountJWTAccessCredentials other) {
                  if (other == null) {
                    return;
                  }
                  if (other.JsonKey.Length != 0) {
                    JsonKey = other.JsonKey;
                  }
                  if (other.TokenLifetimeSeconds != 0UL) {
                    TokenLifetimeSeconds = other.TokenLifetimeSeconds;
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 10: {
                        JsonKey = input.ReadString();
                        break;
                      }
                      case 16: {
                        TokenLifetimeSeconds = input.ReadUInt64();
                        break;
                      }
                    }
                  }
                }

              }

              public sealed partial class GoogleIAMCredentials : pb::IMessage<GoogleIAMCredentials> {
                private static readonly pb::MessageParser<GoogleIAMCredentials> _parser = new pb::MessageParser<GoogleIAMCredentials>(() => new GoogleIAMCredentials());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<GoogleIAMCredentials> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Descriptor.NestedTypes[1]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public GoogleIAMCredentials() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public GoogleIAMCredentials(GoogleIAMCredentials other) : this() {
                  authorizationToken_ = other.authorizationToken_;
                  authoritySelector_ = other.authoritySelector_;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public GoogleIAMCredentials Clone() {
                  return new GoogleIAMCredentials(this);
                }

                /// <summary>Field number for the "authorization_token" field.</summary>
                public const int AuthorizationTokenFieldNumber = 1;
                private string authorizationToken_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string AuthorizationToken {
                  get { return authorizationToken_; }
                  set {
                    authorizationToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "authority_selector" field.</summary>
                public const int AuthoritySelectorFieldNumber = 2;
                private string authoritySelector_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string AuthoritySelector {
                  get { return authoritySelector_; }
                  set {
                    authoritySelector_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other) {
                  return Equals(other as GoogleIAMCredentials);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(GoogleIAMCredentials other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (AuthorizationToken != other.AuthorizationToken) return false;
                  if (AuthoritySelector != other.AuthoritySelector) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode() {
                  int hash = 1;
                  if (AuthorizationToken.Length != 0) hash ^= AuthorizationToken.GetHashCode();
                  if (AuthoritySelector.Length != 0) hash ^= AuthoritySelector.GetHashCode();
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output) {
                  if (AuthorizationToken.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(AuthorizationToken);
                  }
                  if (AuthoritySelector.Length != 0) {
                    output.WriteRawTag(18);
                    output.WriteString(AuthoritySelector);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize() {
                  int size = 0;
                  if (AuthorizationToken.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthorizationToken);
                  }
                  if (AuthoritySelector.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthoritySelector);
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(GoogleIAMCredentials other) {
                  if (other == null) {
                    return;
                  }
                  if (other.AuthorizationToken.Length != 0) {
                    AuthorizationToken = other.AuthorizationToken;
                  }
                  if (other.AuthoritySelector.Length != 0) {
                    AuthoritySelector = other.AuthoritySelector;
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 10: {
                        AuthorizationToken = input.ReadString();
                        break;
                      }
                      case 18: {
                        AuthoritySelector = input.ReadString();
                        break;
                      }
                    }
                  }
                }

              }

              public sealed partial class MetadataCredentialsFromPlugin : pb::IMessage<MetadataCredentialsFromPlugin> {
                private static readonly pb::MessageParser<MetadataCredentialsFromPlugin> _parser = new pb::MessageParser<MetadataCredentialsFromPlugin>(() => new MetadataCredentialsFromPlugin());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<MetadataCredentialsFromPlugin> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor {
                  get { return global::Envoy.Api.V2.Core.GrpcService.Types.GoogleGrpc.Types.CallCredentials.Descriptor.NestedTypes[2]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public MetadataCredentialsFromPlugin() {
                  OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public MetadataCredentialsFromPlugin(MetadataCredentialsFromPlugin other) : this() {
                  name_ = other.name_;
                  Config = other.config_ != null ? other.Config.Clone() : null;
                  _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public MetadataCredentialsFromPlugin Clone() {
                  return new MetadataCredentialsFromPlugin(this);
                }

                /// <summary>Field number for the "name" field.</summary>
                public const int NameFieldNumber = 1;
                private string name_ = "";
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public string Name {
                  get { return name_; }
                  set {
                    name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "config" field.</summary>
                public const int ConfigFieldNumber = 2;
                private global::Google.Protobuf.WellKnownTypes.Struct config_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public global::Google.Protobuf.WellKnownTypes.Struct Config {
                  get { return config_; }
                  set {
                    config_ = value;
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other) {
                  return Equals(other as MetadataCredentialsFromPlugin);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(MetadataCredentialsFromPlugin other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (Name != other.Name) return false;
                  if (!object.Equals(Config, other.Config)) return false;
                  return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode() {
                  int hash = 1;
                  if (Name.Length != 0) hash ^= Name.GetHashCode();
                  if (config_ != null) hash ^= Config.GetHashCode();
                  if (_unknownFields != null) {
                    hash ^= _unknownFields.GetHashCode();
                  }
                  return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output) {
                  if (Name.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(Name);
                  }
                  if (config_ != null) {
                    output.WriteRawTag(18);
                    output.WriteMessage(Config);
                  }
                  if (_unknownFields != null) {
                    _unknownFields.WriteTo(output);
                  }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize() {
                  int size = 0;
                  if (Name.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
                  }
                  if (config_ != null) {
                    size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
                  }
                  if (_unknownFields != null) {
                    size += _unknownFields.CalculateSize();
                  }
                  return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(MetadataCredentialsFromPlugin other) {
                  if (other == null) {
                    return;
                  }
                  if (other.Name.Length != 0) {
                    Name = other.Name;
                  }
                  if (other.config_ != null) {
                    if (config_ == null) {
                      config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
                    }
                    Config.MergeFrom(other.Config);
                  }
                  _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                      case 10: {
                        Name = input.ReadString();
                        break;
                      }
                      case 18: {
                        if (config_ == null) {
                          config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
                        }
                        input.ReadMessage(config_);
                        break;
                      }
                    }
                  }
                }

              }

            }
            #endregion

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
