// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gogoproto/gogo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gogoproto {

  /// <summary>Holder for reflection information generated from gogoproto/gogo.proto</summary>
  public static partial class GogoReflection {

    #region Descriptor
    /// <summary>File descriptor for gogoproto/gogo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GogoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRnb2dvcHJvdG8vZ29nby5wcm90bxIJZ29nb3Byb3RvGiBnb29nbGUvcHJv",
            "dG9idWYvZGVzY3JpcHRvci5wcm90bzo7ChNnb3Byb3RvX2VudW1fcHJlZml4",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zGLHkAyABKAg6PQoVZ29w",
            "cm90b19lbnVtX3N0cmluZ2VyEhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRp",
            "b25zGMXkAyABKAg6NQoNZW51bV9zdHJpbmdlchIcLmdvb2dsZS5wcm90b2J1",
            "Zi5FbnVtT3B0aW9ucxjG5AMgASgIOjcKD2VudW1fY3VzdG9tbmFtZRIcLmdv",
            "b2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxjH5AMgASgJOjAKCGVudW1kZWNs",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkVudW1PcHRpb25zGMjkAyABKAg6QQoUZW51",
            "bXZhbHVlX2N1c3RvbW5hbWUSIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVl",
            "T3B0aW9ucxjRgwQgASgJOjsKE2dvcHJvdG9fZ2V0dGVyc19hbGwSHC5nb29n",
            "bGUucHJvdG9idWYuRmlsZU9wdGlvbnMYmewDIAEoCDo/Chdnb3Byb3RvX2Vu",
            "dW1fcHJlZml4X2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxia",
            "7AMgASgIOjwKFGdvcHJvdG9fc3RyaW5nZXJfYWxsEhwuZ29vZ2xlLnByb3Rv",
            "YnVmLkZpbGVPcHRpb25zGJvsAyABKAg6OQoRdmVyYm9zZV9lcXVhbF9hbGwS",
            "HC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYnOwDIAEoCDowCghmYWNl",
            "X2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxid7AMgASgIOjQK",
            "DGdvc3RyaW5nX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxie",
            "7AMgASgIOjQKDHBvcHVsYXRlX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxl",
            "T3B0aW9ucxif7AMgASgIOjQKDHN0cmluZ2VyX2FsbBIcLmdvb2dsZS5wcm90",
            "b2J1Zi5GaWxlT3B0aW9ucxig7AMgASgIOjMKC29ubHlvbmVfYWxsEhwuZ29v",
            "Z2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKHsAyABKAg6MQoJZXF1YWxfYWxs",
            "EhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKXsAyABKAg6NwoPZGVz",
            "Y3JpcHRpb25fYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKbs",
            "AyABKAg6MwoLdGVzdGdlbl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9w",
            "dGlvbnMYp+wDIAEoCDo0CgxiZW5jaGdlbl9hbGwSHC5nb29nbGUucHJvdG9i",
            "dWYuRmlsZU9wdGlvbnMYqOwDIAEoCDo1Cg1tYXJzaGFsZXJfYWxsEhwuZ29v",
            "Z2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKnsAyABKAg6NwoPdW5tYXJzaGFs",
            "ZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGKrsAyABKAg6",
            "PAoUc3RhYmxlX21hcnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmls",
            "ZU9wdGlvbnMYq+wDIAEoCDoxCglzaXplcl9hbGwSHC5nb29nbGUucHJvdG9i",
            "dWYuRmlsZU9wdGlvbnMYrOwDIAEoCDpBChlnb3Byb3RvX2VudW1fc3RyaW5n",
            "ZXJfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGK3sAyABKAg6",
            "OQoRZW51bV9zdHJpbmdlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9w",
            "dGlvbnMYruwDIAEoCDo8ChR1bnNhZmVfbWFyc2hhbGVyX2FsbBIcLmdvb2ds",
            "ZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiv7AMgASgIOj4KFnVuc2FmZV91bm1h",
            "cnNoYWxlcl9hbGwSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMYsOwD",
            "IAEoCDpCChpnb3Byb3RvX2V4dGVuc2lvbnNfbWFwX2FsbBIcLmdvb2dsZS5w",
            "cm90b2J1Zi5GaWxlT3B0aW9ucxix7AMgASgIOkAKGGdvcHJvdG9fdW5yZWNv",
            "Z25pemVkX2FsbBIcLmdvb2dsZS5wcm90b2J1Zi5GaWxlT3B0aW9ucxiy7AMg",
            "ASgIOjgKEGdvZ29wcm90b19pbXBvcnQSHC5nb29nbGUucHJvdG9idWYuRmls",
            "ZU9wdGlvbnMYs+wDIAEoCDo2Cg5wcm90b3NpemVyX2FsbBIcLmdvb2dsZS5w",
            "cm90b2J1Zi5GaWxlT3B0aW9ucxi07AMgASgIOjMKC2NvbXBhcmVfYWxsEhwu",
            "Z29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLXsAyABKAg6NAoMdHlwZWRl",
            "Y2xfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGLbsAyABKAg6",
            "NAoMZW51bWRlY2xfYWxsEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25z",
            "GLfsAyABKAg6PAoUZ29wcm90b19yZWdpc3RyYXRpb24SHC5nb29nbGUucHJv",
            "dG9idWYuRmlsZU9wdGlvbnMYuOwDIAEoCDo6Cg9nb3Byb3RvX2dldHRlcnMS",
            "Hy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYgfQDIAEoCDo7ChBn",
            "b3Byb3RvX3N0cmluZ2VyEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRp",
            "b25zGIP0AyABKAg6OAoNdmVyYm9zZV9lcXVhbBIfLmdvb2dsZS5wcm90b2J1",
            "Zi5NZXNzYWdlT3B0aW9ucxiE9AMgASgIOi8KBGZhY2USHy5nb29nbGUucHJv",
            "dG9idWYuTWVzc2FnZU9wdGlvbnMYhfQDIAEoCDozCghnb3N0cmluZxIfLmdv",
            "b2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiG9AMgASgIOjMKCHBvcHVs",
            "YXRlEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGIf0AyABKAg6",
            "MwoIc3RyaW5nZXISHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY",
            "wIsEIAEoCDoyCgdvbmx5b25lEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VP",
            "cHRpb25zGIn0AyABKAg6MAoFZXF1YWwSHy5nb29nbGUucHJvdG9idWYuTWVz",
            "c2FnZU9wdGlvbnMYjfQDIAEoCDo2CgtkZXNjcmlwdGlvbhIfLmdvb2dsZS5w",
            "cm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiO9AMgASgIOjIKB3Rlc3RnZW4SHy5n",
            "b29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYj/QDIAEoCDozCghiZW5j",
            "aGdlbhIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiQ9AMgASgI",
            "OjQKCW1hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9u",
            "cxiR9AMgASgIOjYKC3VubWFyc2hhbGVyEh8uZ29vZ2xlLnByb3RvYnVmLk1l",
            "c3NhZ2VPcHRpb25zGJL0AyABKAg6OwoQc3RhYmxlX21hcnNoYWxlchIfLmdv",
            "b2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiT9AMgASgIOjAKBXNpemVy",
            "Eh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJT0AyABKAg6OwoQ",
            "dW5zYWZlX21hcnNoYWxlchIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0",
            "aW9ucxiX9AMgASgIOj0KEnVuc2FmZV91bm1hcnNoYWxlchIfLmdvb2dsZS5w",
            "cm90b2J1Zi5NZXNzYWdlT3B0aW9ucxiY9AMgASgIOkEKFmdvcHJvdG9fZXh0",
            "ZW5zaW9uc19tYXASHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY",
            "mfQDIAEoCDo/ChRnb3Byb3RvX3VucmVjb2duaXplZBIfLmdvb2dsZS5wcm90",
            "b2J1Zi5NZXNzYWdlT3B0aW9ucxia9AMgASgIOjUKCnByb3Rvc2l6ZXISHy5n",
            "b29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYnPQDIAEoCDoyCgdjb21w",
            "YXJlEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGJ30AyABKAg6",
            "MwoIdHlwZWRlY2wSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMY",
            "nvQDIAEoCDoxCghudWxsYWJsZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9w",
            "dGlvbnMY6fsDIAEoCDouCgVlbWJlZBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVs",
            "ZE9wdGlvbnMY6vsDIAEoCDozCgpjdXN0b210eXBlEh0uZ29vZ2xlLnByb3Rv",
            "YnVmLkZpZWxkT3B0aW9ucxjr+wMgASgJOjMKCmN1c3RvbW5hbWUSHS5nb29n",
            "bGUucHJvdG9idWYuRmllbGRPcHRpb25zGOz7AyABKAk6MAoHanNvbnRhZxId",
            "Lmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY7fsDIAEoCToxCghtb3Jl",
            "dGFncxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY7vsDIAEoCTox",
            "CghjYXN0dHlwZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY7/sD",
            "IAEoCTowCgdjYXN0a2V5Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9u",
            "cxjw+wMgASgJOjIKCWNhc3R2YWx1ZRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVs",
            "ZE9wdGlvbnMY8fsDIAEoCTowCgdzdGR0aW1lEh0uZ29vZ2xlLnByb3RvYnVm",
            "LkZpZWxkT3B0aW9ucxjy+wMgASgIOjQKC3N0ZGR1cmF0aW9uEh0uZ29vZ2xl",
            "LnByb3RvYnVmLkZpZWxkT3B0aW9ucxjz+wMgASgIQkUKE2NvbS5nb29nbGUu",
            "cHJvdG9idWZCCkdvR29Qcm90b3NaImdpdGh1Yi5jb20vZ29nby9wcm90b2J1",
            "Zi9nb2dvcHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
